create table
  users (
    id bigint generated by default as identity,
    name text not null,
    password text not null,
    image text not null,
    created_at timestamp with time zone not null default now(),
    token text null,
    constraint users_pkey primary key (id),
    constraint users_name_key unique (name)
  );

create table
  posts (
    id bigint generated by default as identity,
    user_id bigint null,
    message text not null default ''::text,
    created_at timestamp with time zone not null default now(),
    constraint posts_pkey primary key (id)
  );
