version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Whistlebird1337
      - POSTGRES_USER=whistlebird
      - POSTGRES_DB=postgres
  api:
    build:
      context: ./services/api
      args:
        - USER_UID=${CURRENT_UID:-1000}
        - USER_GID=${CURRENT_GID:-1000}
    environment:
      - POSTGRES_CONNECTION_STRING="postgresql://whistlebird:Whistlebird1337@postgres:5432/postgres"
    ports:
      - "127.0.0.1:3000:3000"
