---
swagger: '2.0'
info:
  title: Whistlebird API
  description: Cheap knock-off of Twitter - Coding kata
  version: 0.1.0
definitions: {}
paths:
  "/posts":
    get:
      description: get all posts
      responses:
        '200':
          description: Successful response
          schema:
            description: Successful response
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        name:
                          type: string
                        image:
                          type: string
                    message:
                      type: string
                    created_at:
                      type: string
        '500':
          description: Failing response
          schema:
            description: Failing response
            type: object
            properties:
              error:
                type: string
    post:
      description: create a new post
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            message:
              type: string
      - type: string
        description: user token generated after login
        required: false
        in: header
        name: token
      responses:
        '201':
          description: Successful response
          schema:
            description: Successful response
            type: object
            properties: {}
        '409':
          description: Failing response
          schema:
            description: Failing response
            type: object
            properties:
              error:
                type: string
  "/users":
    get:
      description: get all users
      responses:
        '200':
          description: Successful response
          schema:
            description: Successful response
            type: object
            properties:
              data:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
        '500':
          description: Failing response
          schema:
            description: Failing response
            type: object
            properties:
              error:
                type: string
    post:
      description: create a new user
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            password:
              type: string
      responses:
        '201':
          description: Successful response
          schema:
            description: Successful response
            type: object
            properties: {}
        '500':
          description: Failing response
          schema:
            description: Failing response
            type: object
            properties:
              error:
                type: string
  "/token":
    post:
      description: create token for registered users
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            password:
              type: string
      responses:
        '201':
          description: Successful response
          schema:
            description: Successful response
            type: object
            properties:
              data:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Failing response
          schema:
            description: Failing response
            type: object
            properties:
              error:
                type: string
  "/docs":
    get:
      responses:
        '200':
          description: Default Response
host: localhost
schemes:
- http
consumes:
- application/json
produces:
- application/json
